version: '3.1'

services:
  db:
    image: mariadb:10.6
    container_name: db
    restart: unless-stopped
    ports:
      - "6033:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    restart: unless-stopped
    links:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
  
  api:
    container_name: cmarket-user-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "5000:5000"
    links:
     - db
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URI: mysql+pymysql://root:root@db/courses